name: MagicPitCore
version: '${project.version}'
main: me.dodeedoo.magicpit.MagicPitCore
api-version: 1.19
authors: [ Dodeedoo ]
description: Core plugin for MagicPit
website: dodeedoo.me
commands:
  setStrength:
    permission: "*"